---
# Source: wordpress-stack/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpapp
  labels:
    app: wp
    env: stage
    stack: wordpress
spec:
  selector:
    matchLabels:
      app: wp
      env: stage
      stack: wordpress
  replicas: 3
  template:
    metadata:
      labels:
        app: wp
        env: stage
        stack: wordpress
    spec:
      containers:
      - name: wpapp
        image: msalim22/wp:v2
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: wpapp-configmap
              optional: false
          - secretRef:
              name: wpapp-secret
              optional: false
        ports:
        - containerPort: 80
