---
# Source: wordpress-stack/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wpapp
  labels:
    app: wp
    env: stage
    stack: wordpress
spec:
  ports:
  - port: 80            # the port on which the service is listening
    protocol: TCP
    targetPort: 80      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  type: NodePort
  selector:
    app: wp
    env: stage
    stack: wordpress       # Pod label that service is using to select Pods
